[General]
boreSize = "70mm" # Note: This is later parsed with Unitful
facility = "My awesome institute"
manufacturer = "Me, Myself and I"
name = "DummyScanner"
topology = "FFL" # Of course ;)
gradient = "42T/m" # Note: This is later parsed with Unitful
datasetStore = "~/.mpilab/data"
defaultProtocol = "DummyMeasurement"

[Devices]
initializationOrder = [
    "my_daq_id",
    "my_gauss_id",
    "my_surveillance_unit_id",
    "my_temperature_sensor_id",
]

[Devices.my_daq_id]
deviceType = "DummyDAQ"
samplesPerPeriod = 1000

[Devices.my_gauss_id]
deviceType = "DummyGaussMeter"

[Devices.my_surveillance_unit_id]
deviceType = "DummySurveillanceUnit"

[Devices.my_temperature_sensor_id]
deviceType = "DummyTemperatureSensor"