[GaussMeter]
coordinateTransformation = [0.04, 0.02, -1.0, 0.01, 1.0, 0.01, 1.0, 0.0, 0.03]
range = 1
fast = true
autoRanging = false
# type = "LakeShore"
type = "Dummy"
connection = "/dev/ttyUSB0"

[Robot]
type="Bruker"
connection="RobotServer"
pauseTime=1.0

[Safety]
receiveCoil = "brukerCoil"
robotMount = "hallSensor3D"
clearance = "clearance"
setupName = "hallSensorRegularScanner"

[General]
studyName = "default"
studyExperiment = 0
studyDescription = "n.a."
studySubject = "MNP sample"
studyIsSimulation = false
studyIsCalibration = false
tracerName = ["n.a."]
tracerBatch = ["n.a."]
tracerVendor = ["n.a."]
tracerVolume = [0.0]
tracerConcentration = [0.0]
tracerSolute = ["Fe"]
scannerFacility = "Universitätsklinikum Hamburg-Eppendorf"
scannerOperator = "default"
scannerManufacturer = "Bruker"
scannerName = "Bruker Scanner"
scannerTopology = "FFP MPI"
measIsTransposed = false
measIsBGCorrected = false
measIsTFCorrected = false
measIsFramePermutation = false
measIsFrequencySelection = false
measIsFourierTransformed = false
measIsSpectralLeakageCorrected = false
rpGainSetting = [0,1]
datasetStore = "/opt/data/"
transferFunction = ""
dfWaveform = "sine"
rxUnit = "V"
rxDataConversionFactor = [1.0, 0.0]
