[GaussMeter]
coordinateTransformation = [0, 0, -1, 0, -1, 0, -1, 0, 0]
range = 1
fast = true
autoRanging = false
type = "LakeShore"
connection = "/dev/ttyUSB1"

[General]
transferFunction = "PreinstalledUH"
measIsTransposed = false
measIsFramePermutation = false
tracerVendor = ["n.a."]
scannerOperator = "default"
measIsFrequencySelection = false
studyIsSimulation = false
studySubject = "MNP sample"
measIsFourierTransformed = false
scannerName = "MPS1"
tracerVolume = [0.0]
studyExperiment = 0
studyIsCalibration = false
rxDataConversionFactor = [1.0, 0.0]
tracerConcentration = [0.0]
tracerSolute = ["Fe"]
measIsTFCorrected = false
tracerName = ["n.a."]
studyDescription = "n.a."
tracerBatch = ["n.a."]
scannerTopology = "MPS"
measIsBGCorrected = false
studyName = "default"
datasetStore = "/opt/data/MPS1"
rpGainSetting = [0, 1]
scannerFacility = "Universitätsklinikum Hamburg-Eppendorf"
rxUnit = "V"
scannerManufacturer = "IBI"
measIsSpectralLeakageCorrected = false
dfWaveform = "sine"

[SurveillanceUnit]
type = "Arduino"
connection = "/dev/ttyACM0"

[Robot]
pauseTime = 1.0
stepsPerTurn = 5000
gearSlope = 5
minMaxFreq = [20, 4000]
defaultVel = [40000, 40000, 40000]
defSampleCenterPos = [0.01, 0.0, 0.0]
minMaxVel = [30, 40000]
minMaxAcc = [1, 4000]
defCenterPos = [0.099, 0.128, 0.043000000000000003]
type = "Isel"
connection = "/dev/ttyUSB0"

[Safety]
receiveCoil = "noCoil"
robotMount = "hallSensor"
clearance = "clearance"
setupName = "hallSensornoCoil"

[DAQ]
daq = "RedPitayaScpiNew"
acqFFLinear = false
controlLoopPhaseAccuracy = 1.0
acqFFValues = [0.0]
ip = ["192.168.1.102"]
calibIntToVolt = [0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877]
currTxAmp = [0.1]
currTxPhase = [0.0]
calibFieldToVolt = [23.0]
acqNumBGFrames = 200
acqNumFGFrames = 200
acqNumFFChannels = 1
rxNumChannels = 2
controlPause = 0.8
decimation = 32
acqNumFrames = 1
dfDivider = [4800]
acqNumPeriods = 1
dfStrength = [0.005]
controlLoopAmplitudeAccuracy = 0.04
acqNumAverages = 1
dfPhase = [0.0]
calibRefToField = [0.02]
dfBaseFrequency = 1.25e8
