[GaussMeter]
coordinateTransformation = [0.0, 0.11, -1.0, 0.0, -1.0, 0.01, -1.0, -0.01, 0.0]
range = 1
fast = true
autoRanging = false
type = "LakeShore"
connection = "/dev/ttyUSB1"

[General]
transferFunction = "PreinstalledUH"
measIsTransposed = false
measIsFramePermutation = false
tracerVendor = ["n.a."]
scannerOperator = "default"
measIsFrequencySelection = false
studyIsSimulation = false
studySubject = "MNP sample"
measIsFourierTransformed = false
scannerName = "MPS1"
tracerVolume = [0.0]
studyExperiment = 0
studyIsCalibration = false
rxDataConversionFactor = [1.0, 0.0]
tracerConcentration = [0.0]
tracerSolute = ["Fe"]
measIsTFCorrected = false
tracerName = ["n.a."]
studyDescription = "n.a."
tracerBatch = ["n.a."]
scannerTopology = "MPS"
measIsBGCorrected = false
studyName = "default"
datasetStore = "/opt/data/HeadScanner"
rpGainSetting = [0, 1]
scannerFacility = "Universitätsklinikum Hamburg-Eppendorf"
rxUnit = "V"
scannerManufacturer = "IBI"
measIsSpectralLeakageCorrected = false
dfWaveform = "sine"
calibGridShape = [9,5,1]
calibGridFOV = [90.0,50.0,10.0]
calibGridCenter = [153.0,-11.2,71.0]
calibBGPos = [-60.0,-11.2,71.0]
calibNumBGMeasurements = 2

[SurveillanceUnit]
type =  "Arduino"
#connection = "/dev/ttyACM0"
connection = "/dev/ttyACM0"

[Robot]
pauseTime = 1.0
stepsPerTurn = 5000
gearSlope = 5
minMaxFreq = [20, 4000]
defaultVel = [40000, 40000, 40000]
defSampleCenterPos = [0.01, 0.0, 0.0]
minMaxVel = [30, 40000]
minMaxAcc = [1, 4000]
defCenterPos = [0.099, 0.128, 0.043000000000000003]
type = "Isel"
connection = "/dev/ttyUSB0"

[Safety]
receiveCoil = "noCoil"
robotMount = "hallSensor"
clearance = "clearance"
setupName = "hallSensornoCoil"

[DAQ]
daq = "RedPitayaScpiNew"
controlLoopPhaseAccuracy = 1.0
ip = ["192.168.1.100"]#,"192.168.1.101"]
#ip = ["rp.f049D5.local","rp-f05395.local"]
calibIntToVolt = [0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877]
calibFieldToVolt = [150.9762491038963]
acqNumBGFrames = 200
acqNumFGFrames = 200
rxNumChannels = 1
controlPause = 0.8
controlPhase = true
decimation = 32
acqNumFrames = 1
dfDivider = [4864]
dfStrength = [0.005]
txLimitVolt = [0.8]
controlLoopAmplitudeAccuracy = 0.04
dfPhase = [0.0]
calibRefToField = [0.011627906976744186]
dfBaseFrequency = 1.25e8
acqNumPeriodsPerFrame = 1
acqNumFFChannels = 2
acqFFValues = [1.0,1.0]
acqFFLinear = false
acqFFSequence = "Static"
acqNumAverages = 5000
rxChanIdx = [1]#,3]#,4]
refChanIdx = [2]
dfChanIdx = [1]
rpModulus = [4800,4864,4800,4800]
calibFFCurrentToVolt = 0.08547008547008547
