[GaussMeter]
coordinateTransformation = [0.0, 0.0, -1.0, 0.0, -1.0, 0.0, -1.0, 0.0, 0.0]
range = 1
fast = true
autoRanging = false
type = "LakeShore"
connection = "/dev/ttyUSB1"

[General]
transferFunction = "PreinstalledUH"
measIsTransposed = false
measIsFramePermutation = false
tracerVendor = ["n.a."]
scannerOperator = "default"
measIsFrequencySelection = false
studyIsSimulation = false
studySubject = "MNP sample"
measIsFourierTransformed = false
scannerName = "MPS1"
tracerVolume = [0.0]
studyExperiment = 0
studyIsCalibration = false
rxDataConversionFactor = [1.0, 0.0]
calibGridShape = [9, 5, 1]
tracerConcentration = [0.0]
tracerSolute = ["Fe"]
measIsTFCorrected = false
calibNumBGMeasurements = 2
tracerName = ["n.a."]
studyDescription = "n.a."
tracerBatch = ["n.a."]
scannerTopology = "MPS"
measIsBGCorrected = false
studyName = "default"
datasetStore = "/opt/data/HeadScanner"
rpGainSetting = [0, 1]
calibGridFOV = [0.09, 0.05, 0.01]
calibGridCenter = [0.0, 0.0, 0.0]
scannerFacility = "Universitätsklinikum Hamburg-Eppendorf"
rxUnit = "V"
scannerManufacturer = "IBI"
measIsSpectralLeakageCorrected = false
dfWaveform = "sine"

[SurveillanceUnit]
type = "Arduino"
connection = "/dev/ttyACM0"
#connection = "/dev/ttyACM1"

[Robot]
pauseTime = 1.0
stepsPerTurn = 5000
gearSlope = 5
minMaxFreq = [20, 4000]
defaultVel = [40000, 40000, 40000]
defSampleCenterPos = [0.01, 0.0, 0.0]
defParkPos =[0.420, 0.0, 0.0]
minMaxVel = [30, 40000]
minMaxAcc = [1, 4000]
defCenterPos = [0.0605, 0.1282, 0.1605]
doReferenceCheck = true
type = "Isel"
connection = "/dev/ttyUSB0"

[Safety]
receiveCoil = "headCoil"
robotMount = "deltaSample"
clearance = "clearance"
setupName = "deltaSampleheadCoil"

[DAQ]
daq = "RedPitayaScpiNew"
controlLoopPhaseAccuracy = 0.06
#controlLoopPhaseAccuracy = 0.5
acqFFLinear = false
acqFFValues = [1.0, 1.0]
ip = ["192.168.1.100", "192.168.1.101"]
calibIntToVolt = [0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877]
controlPhase = true
calibFieldToVolt = [104.62607244523313]
calibFFCurrentToVolt = 0.08547008547008547
acqNumBGFrames = 200
rxChanIdx = [1, 3]
acqNumFGFrames = 200
acqNumFFChannels = 2
rpModulus = [4800, 4864, 4800, 4800]
rxNumChannels = 1
controlPause = 0.01
decimation = 64
acqNumFrames = 1
dfDivider = [4864]
acqNumPeriodsPerFrame = 1
dfStrength = [0.005]
refChanIdx = [2]
controlLoopAmplitudeAccuracy = 0.001
#controlLoopAmplitudeAccuracy = 0.003
acqNumAverages = 200
dfPhase = [0.0]
dfChanIdx = [1]
calibRefToField = [0.0159295]
acqFFSequence = "Static"
txLimitVolt = [0.8]
dfBaseFrequency = 1.25e8
