[GaussMeter]
coordinateTransformation = [0.0, 0.0, -1.0, 0.0, -1.0, 0.0, -1.0, 0.0, 0.0]
range = 1
fast = true
autoRanging = false
type = "LakeShore"
connection = "/dev/ttyUSB1"

[General]
measIsTransposed = false
measIsFramePermutation = false
tracerVendor = ["n.a."]
scannerOperator = "default"
measIsFrequencySelection = false
studyIsSimulation = false
studySubject = "MNP sample"
measIsFourierTransformed = false
scannerName = "MPS1"
tracerVolume = [0.0]
studyExperiment = 0
studyIsCalibration = false
rxDataConversionFactor = [1.0, 0.0]
calibGridShape = [9, 5, 1]
tracerConcentration = [0.0]
tracerSolute = ["Fe"]
measIsTFCorrected = false
calibNumBGMeasurements = 2
tracerName = ["n.a."]
studyDescription = "n.a."
tracerBatch = ["n.a."]
scannerTopology = "MPS"
measIsBGCorrected = false
studyName = "default"
datasetStore = "/opt/data/HeadScanner"
maxTemperature = 55.0
rpGainSetting = [0, 1]
calibGridFOV = [0.09, 0.05, 0.01]
calibGridCenter = [0.0, 0.0, 0.0]
scannerFacility = "Universitätsklinikum Hamburg-Eppendorf"
rxUnit = "V"
scannerManufacturer = "IBI"
measIsSpectralLeakageCorrected = false
dfWaveform = "sine"

[SurveillanceUnit]
type = "Arduino"
connection = "/dev/ttyACM0"

[Robot]
pauseTime = 1.0
defaultRefVel = [40000, 40000, 40000]
stepsPerTurn = 5000
gearSlope = 5
minMaxFreq = [20, 4000]
defaultVel = [40000, 40000, 40000]
defSampleCenterPos = [0.01, 0.0, 0.0]
minMaxVel = [30, 40000]
minMaxAcc = [1, 4000]
defCenterPos = [0.0745, 0.1282, 0.0755]
doReferenceCheck = true
defParkPos = [0.42, 0.1282, 0.0755]
defAssemblePos = [0.42, 0.0, 0.25]
type = "Isel"
connection = "/dev/ttyUSB0"

[Safety]
receiveCoil = "headCoil"
robotMount = "deltaSample3D"
clearance = "clearance"
setupName = "deltaSampleheadCoil"

[DAQ]
daq = "RedPitayaScpiNew"
controlLoopPhaseAccuracy = 0.2
acqFFLinear = false
acqFFValues = [1.0, 1.0]
ip = ["192.168.1.100", "192.168.1.101"]
calibIntToVolt = [0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877]
controlPhase = true
calibFieldToVolt = [135]
calibFFCurrentToVolt = 0.08547008547008547
acqNumBGFrames = 200
rxChanIdx = [1, 3, 4]
acqNumFGFrames = 200
acqNumFFChannels = 2
rpModulus = [4800, 4864, 4800, 4800]
rxNumChannels = 1
controlPause = 0.01
decimation = 64
acqNumFrames = 1
dfDivider = [4864]
acqNumPeriodsPerFrame = 1
dfStrength = [0.006]
refChanIdx = [2]
controlLoopAmplitudeAccuracy = 0.01
acqNumAverages = 100
dfPhase = [0.0]
dfChanIdx = [2]
calibRefToField = [0.015170670037926675]
ffRampUpFraction = 0.5
acqFFSequence = "Static"
txLimitVolt = [0.8]
dfBaseFrequency = 1.25e8
ffRampUpTime = 1.5
