[GaussMeter]
coordinateTransformation = [0, 0, -1, 0, -1, 0, -1, 0, 0]
range = 1
fast = true
autoRanging = false
type = "LakeShore"
connection = "/dev/ttyUSB1"

[Robot]
pauseTime = 1.0
stepsPerTurn = 5000
gearSlope = 5
minMaxFreq = [20, 4000]
defaultVel = [40000, 40000, 40000]
defSampleCenterPos = [0.01, 0.0, 0.0]
minMaxVel = [30, 40000]
minMaxAcc = [1, 4000]
defCenterPos = [0.1, 0.14100000000000001, 0.005]
type = "Isel"
connection = "/dev/ttyUSB0"

[Safety]
receiveCoil = "noCoil"
robotMount = "hallSensor"
clearance = "clearance"
setupName = "hallSensornoCoil"

[DAQ]
ip = ["192.168.1.21", "192.168.1.22"]
#ip = ["10.167.6.172"]
daq = "RedPitayaNew"
acqNumFrames = 1
acqNumFGFrames = 200
acqNumBGFrames = 200
acqNumAverages = 1
decimation = 32
calibFieldToVolt = 23.0
#calibRefToField = [0.05]
calibRefToField = [0.020, 0.020]
calibIntToVolt = [1.2957305E-4, 0.015548877, 1.2957305E-4, 0.015548877, 1.2957305E-4, 0.015548877, 1.2957305E-4, 0.015548877]
dfStrength = [5e-3, 2e-3]
dfPhase = [0.0, 0.0]
dfBaseFrequency = 125e6
dfDivider = [4800, 4800]
rxNumChannels = 2
controlPause = 0.8
acqNumFFChannels = 1
acqFFValues = [0.0]#,0.1,0.2,0.3]#,0.4,0.5,0.6,0.7]#,0.4,0.6]
acqNumPeriods = 1
acqFFLinear = false
controlLoopPhaseAccuracy = 1.0
controlLoopAmplitudeAccuracy = 0.04
currTxAmp = [0.1,0.1]
currTxPhase = [0.0,0.0]


[General]
studyName = "default"
studyExperiment = 0
studyDescription = "n.a."
studySubject = "MNP sample"
studyIsSimulation = false
studyIsCalibration = false
tracerName = ["n.a."]
tracerBatch = ["n.a."]
tracerVendor = ["n.a."]
tracerVolume = [0.0]
tracerConcentration = [0.0]
tracerSolute = ["Fe"]
scannerFacility = "Universitätsklinikum Hamburg-Eppendorf"
scannerOperator = "default"
scannerManufacturer = "IBI"
scannerName = "MPS1"
scannerTopology = "MPS"
measIsTransposed = false
measIsBGCorrected = false
measIsTFCorrected = false
measIsFramePermutation = false
measIsFrequencySelection = false
measIsFourierTransformed = false
measIsSpectralLeakageCorrected = false
rpGainSetting = [0,1]
datasetStore = "/opt/data/MPS1"
transferFunction = "PreinstalledUH"
dfWaveform = "sine"
rxUnit = "V"
rxDataConversionFactor = [1.0, 0.0]
