[Robot]
type="Isel"
connection="/dev/ttyUSB0"
pauseTime=1.0
minMaxVel = [30,40000]
minMaxAcc = [1,4000]
minMaxFreq = [20,4000]
stepsPerTurn = 5000
gearSlope = 5 # 1 turn equals 5mm feed
defaultVel = [40000,40000,40000]
defCenterPos = [0.095,0.113,0.115] # Hallsensor in center of magnetic field in meter!
defSampleCenterPos = [0.010,0.0,0.0] # relative geometry distance to of sample mount to Hallsensor mount
[Safety]
setupName = "hallSensornoCoil"
receiveCoil = "noCoil"
robotMount = "hallSensor"
clearance = "clearance"
