[DAQ]
ip = ["192.168.1.100"]
#ip = ["192.168.1.9"]
#ip = ["10.167.6.172"]
daq = "RedPitayaScpiNew"
#daq = "RedPitayaNew"
acqNumFrames = 1
acqNumFGFrames = 200
acqNumBGFrames = 200
acqNumAverages = 1
decimation = 16
calibFieldToVolt = [23.0]
#calibRefToField = [0.05]
calibRefToField = [0.02884]
calibIntToVolt = [1.2957305E-4, 0.015548877, 0.002591461, 0.31097754]
dfStrength = [20e-3]
dfPhase = [0.0]
dfBaseFrequency = 125e6
dfDivider = [4800]
rxNumChannels = 1
controlPause = 0.8
acqNumFFChannels = 1
acqFFValues = [1.0]
acqNumPeriods = 1
acqFFLinear = false
controlLoopPhaseAccuracy = 1.0
controlLoopAmplitudeAccuracy = 0.04
currTxAmp = [0.1]
currTxPhase = [0.0]


[General]
studyName = "default"
studyExperiment = 0
studyDescription = "n.a."
studySubject = "MNP sample"
studyIsSimulation = false
studyIsCalibration = false
tracerName = ["n.a."]
tracerBatch = ["n.a."]
tracerVendor = ["n.a."]
tracerVolume = [0.0]
tracerConcentration = [0.0]
tracerSolute = ["Fe"]
scannerFacility = "Universitätsklinikum Hamburg-Eppendorf"
scannerOperator = "default"
scannerManufacturer = "IBI"
scannerName = "MPS1"
scannerTopology = "MPS"
measIsTransposed = false
measIsBGCorrected = false
measIsTFCorrected = false
measIsFramePermutation = false
measIsFrequencySelection = false
measIsFourierTransformed = false
measIsSpectralLeakageCorrected = false
rpGainSetting = [0,1]
datasetStore = "/opt/data/MPS1"
transferFunction = "PreinstalledUH"
dfWaveform = "sine"
rxUnit = "V"
rxDataConversionFactor = [1.0, 0.0]
