[DAQ]
ip = ["192.168.1.100"]
daq = "RedPitayaScpiNew"
acqNumFrames = 10
acqNumFGFrames = 200
acqNumBGFrames = 200
acqNumAverages = 1000
decimation = 16
calibFieldToVolt = [20.509]
calibRefToField = [0.0133]
calibIntToVolt = [1.2957305E-4, 0.015548877, 0.002591461, 0.31097754]
dfStrength = [20e-3]
dfPhase = [0.0]
dfBaseFrequency = 125e6
dfDivider = [4864]
rxNumChannels = 1
controlPause = 0.8
acqNumFFChannels = 1
acqFFValues = [1.0]
acqFFSequence = "NoneFile"
acqNumPeriodsPerFrame = 1
acqFFLinear = false
controlLoopPhaseAccuracy = 0.1
controlLoopAmplitudeAccuracy = 0.01
txLimitVolt = [0.6]
rxChanIdx = [1]#,3,4]
refChanIdx = [2]
dfChanIdx = [1]
rpModulus = [4800,4864,4800,4800]

[Robot]
type="Dummy"
pauseTime=1.0


[General]
studyName = "default"
studyExperiment = 0
studyDescription = "n.a."
studySubject = "MNP sample"
studyIsSimulation = false
studyIsCalibration = false
tracerName = ["n.a."]
tracerBatch = ["n.a."]
tracerVendor = ["n.a."]
tracerVolume = [0.0]
tracerConcentration = [0.0]
tracerSolute = ["Fe"]
scannerFacility = "Universitätsklinikum Hamburg-Eppendorf"
scannerOperator = "default"
scannerManufacturer = "IBI"
scannerName = "MPS1"
scannerTopology = "MPS"
measIsTransposed = false
measIsBGCorrected = false
measIsTFCorrected = false
measIsFramePermutation = false
measIsFrequencySelection = false
measIsFourierTransformed = false
measIsSpectralLeakageCorrected = false
rpGainSetting = [0,1]
<<<<<<< HEAD
datasetStore = "/home/labuser" #"/opt/data/MPS1"
transferFunction = "PreinstalledUH"
=======
datasetStore = "/opt/data/MPS1"
transferFunction = "MPSTF"
>>>>>>> 9375e758066b195c64f90ab5757ce438a2fdddd8
dfWaveform = "sine"
rxUnit = "V"
rxDataConversionFactor = [1.0, 0.0]
