[DAQ]
ip = ["192.168.1.20"]
#ip = ["10.167.6.172"]
daq = "RedPitayaNew"
acqNumFGFrames = 200
acqNumBGFrames = 200
acqNumAverages = 100
decimation = 16
calibFieldToVolt = 0.5#23.0
#calibRefToField = [0.05]
calibRefToField = [0.020]
calibIntToVolt = [1.2957305E-4, 0.015548877, 1.2957305E-4, 0.015548877]
studyName = "default"
studyExperiment = 0
studyDescription = "n.a."
studySubject = "MNP sample"
tracerName = ["n.a."]
tracerBatch = ["n.a."]
tracerVendor = ["n.a."]
tracerVolume = [0.0]
tracerConcentration = [0.0]
tracerSolute = ["Fe"]
scannerFacility = "Universitätsklinikum Hamburg-Eppendorf"
scannerOperator = "default"
scannerManufacturer = "IBI"
scannerName = "MPS1"
scannerTopology = "MPS"
dfStrength = [5e-3]
dfPhase = [0.0]
dfBaseFrequency = 125e6
dfDivider = [4096] #[16384]#[4096]
rxNumChannels = 1
controlPause = 0.8
acqNumFFChannels = 1
acqFFValues = [0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7]#,0.4,0.6]
acqNumPeriods = 8
acqFFLinear = false
controlLoopPhaseAccuracy = 1
controlLoopAmplitudeAccuracy = 0.04
rpGainSetting = [0,1]
datasetStore = "/opt/data/MPS1"
transferFunction = "PreinstalledUH"
#transferFunction2 = "MPS1"
dfWaveform = "sine"
rxUnit = "V"
rxDataConversionFactor = [1.0, 0.0]
measIsTransposed = false
measIsBGCorrected = false
measIsTFCorrected = false
measIsFramePermutation = false
measIsFrequencySelection = false
measIsFourierTransformed = false
measIsSpectralLeakageCorrected = false
studyIsSimulation = false
studyIsCalibration = false
