[GaussMeter]
type = "Dummy"

[General]
allowDFWaveformChanges = true
measIsTransposed = false
measIsFramePermutation = false
tracerVendor = ["n.a."]
scannerOperator = "default"
measIsFrequencySelection = false
studyIsSimulation = false
studySubject = "MNP sample"
measIsFourierTransformed = false
scannerName = "MPS1"
tracerVolume = [0.0]
studyExperiment = 0
studyIsCalibration = false
rxDataConversionFactor = [1.0, 0.0]
tracerConcentration = [0.0]
tracerSolute = ["Fe"]
measIsTFCorrected = false
tracerName = ["n.a."]
studyDescription = "n.a."
tracerBatch = ["n.a."]
scannerTopology = "MPS"
measIsBGCorrected = false
studyName = "default"
datasetStore = "/opt/data/HeadScanner"
rpGainSetting = [0, 1]
scannerFacility = "Universitätsklinikum Hamburg-Eppendorf"
rxUnit = "V"
scannerManufacturer = "IBI"
measIsSpectralLeakageCorrected = false
dfWaveform = "sine"
calibGridShape = [3,2,1]
calibGridFOV = [0.10,0.10,0.10]
calibGridCenter = [0.0,0.0,0.0]
calibNumBGMeasurements = 2
maxTemperature = 55.0
pauseTime = 0.0


[SurveillanceUnit]
type = "Dummy"


[Robot]
type="Dummy"
pauseTime=0.0

[Safety]
receiveCoil = "headCoil"
robotMount = "deltaSample"
clearance = "clearance"
setupName = "deltaSampleheadCoil"

[DAQ]

daq = "RedPitayaScpiNew"
#ip = ["rp-f04972.local"]
ip = ["192.168.178.52"]
calibIntToVolt = [0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877]
acqNumBGFrames = 1
acqNumFGFrames = 1
rxNumChannels = 1
triggerMode = "EXTERNAL"
#"INTERNAL"
controlPause = 0.2
controlPhase = false
# true
decimation = 32
acqNumFrames = 1
dfDivider = [4864,4800]
dfStrength = [0.005]
txLimitVolt = [0.8, 0.8] # dim D
controlLoopAmplitudeAccuracy = 0.00001
controlLoopPhaseAccuracy = 0.01
dfPhase = [0.0, 0.0]
calibRefToField = [0.1, 0.1] # dim D
calibFieldToVolt = [10, 10] # dim D
#calibRefToField = [1.0, 1.0] 
#calibFieldToVolt = [1.0, 1.0] 
dfBaseFrequency = 1.25e8
acqNumPeriodsPerFrame = 1
#acqNumFFChannels = 1
#acqFFValues = []
acqFFSequence = "None"
acqFFLinear = false
acqNumAverages = 1
acqNumFrameAverages = 1
rxChanIdx = [1,2]
#rxChanIdx = [1,3,4,5,6]
refChanIdx = [1,2]
dfChanIdx = [1,2]
calibFFCurrentToVolt = [0.04547008547008547,0.04547008547008547]
#ffRampUpTime = 0.01
#ffRampUpFraction = 0.8
ffRampUpFraction = 0.6
ffRampUpTime = 0.2
jumpSharpness = 0.1
passPDMToFastDAC = [false, false]
