name = "MagneticFieldMeasurement"
type = "RobotBasedMagneticFieldStaticProtocol"
description = "A magnetic field measurement."
targetScanner = "MagneticFieldMeasurement"

positions.type = "RegularGridPositions"
positions.shape = [5, 1, 5]
positions.fov = ["3.0mm", "3.0mm", "3.0mm"]
positions.center = ["5.0mm", "5.0mm", "5.0mm"]