name = "MagneticFieldMeasurement"
type = "RobotBasedMagneticFieldStaticProtocol"
description = "A magnetic field measurement."
targetScanner = "MagneticFieldMeasurement"

positions.type = "RegularGridPositions"
positions.shape = [3, 1, 3]
positions.fov = ["5.0mm", "5.0mm", "5.0mm"]
positions.center = ["5.0mm", "50.0mm", "50.0mm"]

postMoveWaitTime = "1.0s"