[General]
name = "MagneticFieldMeasurement"
facility = "Fraunhofer IMTE"
manufacturer = "Schumacher et al."
topology = "FFL"
gradient = "5T/m"
boreSize = "40mm"
datasetStore = "./tmp/TestDummyScannerStore"

[Devices]
initializationOrder = [
    "gaussmeter",
    "robot"
]

[Devices.gaussmeter]
deviceType = "LakeShoreF71GaussMeter"
comport = "COM4"
baudrate = 115200
measurementMode = "DC"

[Devices.robot]
deviceType = "IselRobot"
stepsPermm = 160
serial_port = "COM5"
#scannerCoordAxes = [[1,0,0] [0,1,0] [0,0,1]]
#scannerCoordOrigin = ["0.0mm", "0.0mm", "0.0mm"]
referenceOrder = "zxy"
movementOrder = "zxy"
namedPositions.park = ["0.0mm", "0.0mm", "50.0mm"]
