name = "RobotBasedSystemMatrix"
type = "RobotBasedSystemMatrixProtocol"
description = "An acquisition with the Red Pitaya"
targetScanner = "SimpleRedPitayaScanner"

waitTime = 0.5
bgFrames = 1
bgFrameAverages = 1

[Positions]
positionsType = "RegularGridPositions"
positionsShape = [4,3,1]
positionsFov = [0.1,0.1,0.1]
positionsCenter = [0.0,0.0,0.0]
