[General]
boreSize = "1337mm"
facility = "My awesome institute"
manufacturer = "Me, Myself and I"
name = "SimpleRedPitayaScanner"
topology = "FFL"
gradient = "42T/m"
#datasetStore = "/opt/data/HeadScanner"
datasetStore = "~/Documents/DatasetStores/store1"
defaultSequence = "ElectricalSequence"
defaultProtocol = "RobotBasedSystemMatrixCalibration"

[Devices]
initializationOrder = [
  "rp_cluster",
  "measurement_controller",
  "dummy_robot",
  "dummy_surveillance"
]

[Devices.dummy_robot]
deviceType = "DummyRobot"

[Devices.dummy_surveillance]
deviceType = "DummySurveillanceUnit"

[Devices.rp_cluster]
deviceType = "RedPitayaDAQ"
dependencies = []
#ips = ["192.168.2.16"] #, "192.168.2.17"]
#ips = ["192.168.178.52"] #, "192.168.178.53"]
ips = ["192.168.1.100"] #, "192.168.1.101"]
calibFFCurrentToVolt = [0.7, 0.7]
calibIntToVolt = [0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877]
calibFieldToVolt = [20, 20]
#passPDMToFastDAC = [false] #, false]

[Devices.rp_cluster.chanx]
type = "tx"
channel = 1
limitPeak = "1V"
sinkImpedance = "HIGH"
#allowedWaveforms = ["sine"]
calibration = "0.1V/mT"
feedback.channelID = "feedback_main"
feedback.calibration = "10mT/V"
passPDMToFastDAC = true

[Devices.rp_cluster.chany]
type = "tx"
channel = 2
limitPeak = "1V"
sinkImpedance = "HIGH"
#allowedWaveforms = ["sine"]
calibration = "0.1V/mT"
feedback.channelID = "feedback_main"
feedback.calibration = "10mT/V"

[Devices.rp_cluster.rx_main]
type = "rx"
channel = 2
limitPeak = "1V"

[Devices.rp_cluster.rx_side]
type = "rx"
channel = 2
limitPeak = "1V"

[Devices.rp_cluster.feedback_main]
type = "rx"
channel = 2
limitPeak = "1V"

[Devices.measurement_controller]
deviceType = "MeasurementController"
dependencies = [
  "rp_cluster"
]
producerThreadID = 2
consumerThreadID = 3

