[General]
name = "2DSequence"
description = "Precise description."
targetScanner = "HeadScanner"
baseFrequency = "125.0MHz"
triggered = false

[Fields]

[Fields.df]
safeStartInterval = "0.5s"
safeEndInterval = "0.5s"
safeErrorInterval = "0.5s"
control = true
decouple = true

[Fields.df.chanx]
offset = "0.0mT"

[Fields.df.chanx.c1]
divider = 4800
amplitude = ["0.02T"]
phase = ["0.0rad"]
waveform = "sine"

[Fields.df.chanx.c2]
divider = 4864
amplitude = ["0.01T"]

[Fields.df.chany]
offset = "0.0mT"

[Fields.df.chany.c1]
divider = 4800
amplitude = ["0.02T"]
phase = ["0.0rad"]
waveform = "sine"

[Fields.df.chany.c2]
divider = 4864
amplitude = ["0.01T"]

[Fields.ff]
safeStartInterval = "0.5s"
safeEndInterval = "0.5s"
safeErrorInterval = "0.5s"
control = true
decouple = true


[Fields.ff.ffx]
dividerSteps = 3648000
divider = 182400000
amplitude = "5.0V"
offset = "5.0V"
phase = "0.0rad"
waveform = "sine"

[Acquisition]
channels = ["rx_main", "rx_side"]
bandwidth = "7.8125MHz"
numPeriodsPerFrame = 1
numFrames = 20
numAverages = 1
numFrameAverages = 1
