[General]
name = "SimpleRedPitayaSequence"
description = "Precise description."
targetScanner = "TestRedPitayaScanner"
baseFrequency = "125.0MHz"

[Fields]

[Fields.my_df]
safeStartInterval = "0.5s"
safeEndInterval = "0.5s"
safeErrorInterval = "0.5s"
control = true
decouple = true

[Fields.df.tx_main]
waveform = "sine"
offset = "0.0mT"

[Fields.df.tx_main.main_component]
divider = 4800
amplitude = ["0.02T"]
phase = ["0.0rad"]


[Fields.ff]
safeStartInterval = "0.5s"
safeEndInterval = "0.5s"
safeErrorInterval = "0.5s"
control = true
decouple = true

[Fields.ff.ffx]
stepsPerCycle = 10
amplitude = ["5.0V", "6.0V", "7.0V", "8.0V", "9.0V"]

[Fields.ff.ffy]
stepsPerCycle = 10
amplitude = ["5.0V", "6.0V", "7.0V", "8.0V", "9.0V"]

[Acquisition]
channels = ["rx_main"]
bandwidth = "7.8125MHz"
numPeriodsPerFrame = 1

[Acquisition.Foreground]
numFrames = 20
numAverages = 1
numFrameAverages = 1

[Acquisition.Background]
numFrames = 2
numAverages = 5
numFrameAverages = 3