[General]
boreSize = "230mm"
facility = "Universitätsklinikum Hamburg-Eppendorf"
manufacturer = "IBI"
name = "HeadScanner"
topology = "FFP"
gradient = "42T/m"
datasetStore = "/opt/data/HeadScanner"
defaultSequence = "1DSequence"
defaultProtocol = "MPIMeasurement"
producerThreadID = 2
consumerThreadID = 3
protocolThreadID = 4

[Devices]
initializationOrder = [
  "rp_cluster",
  "tx_controller",
  "surveillance",
  "su_temp",
  "robot",
  "collision_module"
]

# DAQ
[Devices.rp_cluster]
deviceType = "RedPitayaDAQ"
dependencies = []
ips = ["192.168.1.103","192.168.1.104","192.168.1.105"]
calibIntToVolt = [0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00026, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877, 0.00012957305, 0.015548877]
calibFFCurrentToVolt = [0.027061248, 0.026531]

[Devices.rp_cluster.chanx]
type = "tx"
channel = 1
limitPeak = "1V"
sinkImpedance = "HIGH"
#allowedWaveforms = ["sine"]
calibration = "1V/T"
feedback.channelID = "feedback_main"
feedback.calibration = "1T/V"
passPDMToFastDAC = true

[Devices.rp_cluster.chany]
type = "tx"
channel = 2
limitPeak = "1V"
sinkImpedance = "HIGH"
#allowedWaveforms = ["sine"]
calibration = "1V/T"

[Devices.rp_cluster.rx_main]
type = "rx"
channel = 1
limitPeak = "1V"

[Devices.rp_cluster.rx_side]
type = "rx"
channel = 2
limitPeak = "1V"

[Devices.rp_cluster.feedback_main]
type = "rx"
channel = 2
limitPeak = "1V"

[Devices.rp_cluster.ffx]
type = "txSlow"
channel = 1

[Devices.rp_cluster.ffy]
type = "txSlow"
channel = 2

[Devices.tx_controller]
deviceType = "TxDAQController"
dependencies = ["rp_cluster"]
phaseAccuracy = 0.1
amplitudeAccuracy = 0.01
controlPause = 0.2
maxControlSteps = 10
correctCrossCoupling = false

# Robot
[Devices.robot]
deviceType = "IselRobot"
dependencies = ["collision_module"]
baudrate = 19200
stepsPermm = 1000
serial_port = "/dev/ttyUSB0"
defaultRefVel = ["20mm/s", "20mm/s", "20mm/s"]
axisRange = [["0mm", "400mm"], ["0mm", "390mm"], ["0mm", "180mm"]]
defaultVel = ["20mm/s", "20mm/s", "20mm/s"]
invertAxes = [false, false, true]
minMaxVel = [30,40000]
referenceOrder = "zyx"

[Devices.robot.coordinateSystem]
origin = ["125.5mm", "125.5mm", "75.5mm"]

[Devices.robot.namedPositions]
origin = ["0mm", "0mm", "0mm"]
park = ["325.5mm", "125.5mm", "75.5mm"]

[Devices.collision_module]
deviceType = "SimpleBoreCollisionModule"
objGeometry.type = "Circle"
objGeometry.diameter = "10mm"
objGeometry.name = "Delta sample"
scannerDiameter = "170mm"
clearance = "1mm"
minMaxBoreAxis = ["-90mm","Inf*mm"]


# Surveillance Unit
[Devices.surveillance]
deviceType = "ArduinoSurveillanceUnitExternalTemp"
dependencies = ["su_temp"]
portAdress = "/dev/ttyACM1"

[Devices.su_temp]
deviceType = "ArduinoTemperatureSensor"
portAdress = "/dev/ttyACM0"
numSensors = 16
maxTemps = [41,42,43,44,45,46,47,48,49,50,51,52,53,60,60,60]
selectSensors = [4,6,8,9]
nameSensors = ["RX1","RX2","RX3","TX1/1","TX1/2","TX2/1","TX2/2", "SefoCoilRight", "SefoCoilLeft", "ICN X", "ICN Z", "n.c.", "(Rack)", "SefoCoreRight", "SefoCoreLeft","SefoCabin"]
