[General]
boreSize = "1337mm"
facility = "Universitätsklinikum Hamburg-Eppendorf"
manufacturer = "IBI"
name = "HeadScanner"
topology = "FFP"
gradient = "42T/m"
#datasetStore = "/opt/data/HeadScanner"
datasetStore = "/home/niklas/Documents/DatasetStores/store1"
defaultSequence = "1DSequence"
defaultProtocol = "MPIMeasurement"
producerThreadID = 2
consumerThreadID = 3
protocolThreadID = 4

[Devices]
initializationOrder = [
#  "rp_cluster",
  "robot"
]

[Devices.my_daq_id]
deviceType = "SimpleSimulatedDAQ"
dependencies = [
  "simulation_controller" ]
#ip = "127.0.0.1"
temperatureRise.tx_main = "10K"
temperatureRiseSlope.tx_main = "0.005s"
phaseChange.tx_main  = "0.1°/K"
amplitudeChange.tx_main  = "0.05mT/K"

[Devices.my_daq_id.tx_main]
type = "tx"
channel = 1
limitPeak = "1V"
sinkImpedance = "HIGH"
#allowedWaveforms = ["sine"]
calibration = "0.1V/mT"
feedback.channelID = "feedback_main"
feedback.calibration = "10mT/V"


[Devices.simulation_controller]
deviceType = "SimulationController"
initialCoilTemperatures.tx_main = "20.0°C"

[Devices.my_daq_id.rx_main]
type = "rx"
channel = 1
limitPeak = "1V"

[Devices.my_daq_id.feedback_main]
type = "rx"
channel = 2
limitPeak = "1V"

[Devices.robot]
deviceType = "IselRobot"
baudrate = 19200
stepsPermm = 1000
serial_port = "/dev/ttyUSB0"
scannerCoordOrigin = ["125.5mm", "125.5mm", "75.5mm"]
defaultRefVel = ["10mm/s", "10mm/s", "10mm/s"]
axisRange = [["0mm", "400mm"], ["0mm", "390mm"], ["0mm", "180mm"]]
defaultVel = ["10mm/s", "10mm/s", "10mm/s"]
invertAxes = [false, false, true]
minMaxVel = [30,40000]
referenceOrder = "zyx"

[Devices.robot.namedPositions]
origin = ["0mm", "0mm", "0mm"]
#park = ["420mm", "125.5mm", "105.5mm"]